### ISSUE TITLE
`RECEIVE_RAW_CREATED_MESSAGE` event is never handled

### ISSUE THREAD

**Issue by coodoo** [facebook/flux#32] opened 2014-08-15 04:38 UTC
Just wondering what happens when `RECEIVE_RAW_CREATED_MESSAGE` was dispatched, currently in the code base it was *not* handled anywhere.

Also, what if `ChatWebAPIUtils.createMessage()` received error from the XHR call to server, what happens next? Should the data already in Stores and Views be rolled back?

**Comment by mczepiel** [comment] 2015-01-16 22:06
FWIW, even if you only implement the happy path acceptance of the "confirmed" message I think it would    make this example feel more complete. Right now the complete absence of any handler for this action led me to hunt around to see if I was missing something.

A comment about the `RECEIVE_RAW_CREATED_MESSAGE_FAILURE` being left as an exercise for the reader would be fine but I don't think closing the loop of accepting the confirmed message from the "server" would over complicate this.

I could take care of that for you with a PR but I have another [related question](https://groups.google.com/forum/#!topic/reactjs/t7q_SW-77uY) I posted on the google group where I need some clarification.

**Comment by sharathprabhal** [comment] 2015-07-16 11:39
+1

**Comment by facebook-github-bot-6** [comment] 2015-08-05 18:01
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment] 2015-11-18 22:02
Looks like original issue is resolved so closing this out. If there is a specific aspect of the example you feel could be improved (such as adding a comment) a PR would be great.

**Closed by kyldvs** 2015-11-18 22:02 UTC
