### ISSUE TITLE
Tutorial Todo using deprecated react-boilerplate / npm install fails

### ISSUE THREAD

**Issue by PaulMakepeace** [facebook/flux#282] opened 2015-09-17 19:41 UTC
https://facebook.github.io/flux/docs/todo-list.html is using react-boilerplate which is apparently deprecated according to https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

```
$ npm install
npm WARN package.json react-boilerplate@0.2.0 No repository field.
npm WARN package.json react-boilerplate@0.2.0 license should be a valid SPDX license expression
npm WARN deprecated react-tools@0.8.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
/
> fsevents@0.2.1 install /Users/makepeace/react-boilerplate/node_modules/jsxc/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[goes on and on]
```

**Comment by goofyahead** [comment] 2015-09-24 16:05
:+1:

**Comment by garrettboatman** [comment] 2015-09-25 21:16
:+1:

**Comment by kmichal** [comment] 2015-09-28 03:29
:thumbsup:

**Comment by batesy** [comment] 2015-10-02 01:13
Would love to get this working. Any fix on the horizon?

**Comment by kyldvs** [comment] 2015-10-02 04:52
Hmm, @fisherwebdev what do you think about taking this as a chance to upgrade examples to ES6 as well?

**Comment by destan** [comment] 2015-10-02 12:58
I was able to build it with following versions of node and npm:

* node `v0.12.7`
* npm `2.11.3`

`npm install` just works with those version. I use `nvm` to change node version.

**Comment by destan** [comment] 2015-10-02 13:00
I was able to build it with following versions of node and npm:

node v0.12.7
npm 2.11.3
npm install just works with those version. I use nvm to change node version.

**Comment by geezmo** [comment] 2015-10-07 14:42
Same node/npm as @destan but I wasn't able to run npm install. :(

**Comment by justwy** [comment] 2015-10-11 12:36
jest-cli expected a lower version node. Upgrade jest-cli works for me (I am using node version 4.0.0)
npm install jest-cli --save-dev
npm install

**Comment by trojanc** [comment] 2015-10-14 17:39
What @justwy suggested works.
Just first delete the node_modules directory if it failed already

**Comment by cpdean** [comment] 2015-10-18 19:17
someone should submit a pull request updating the dependencies.  this is an easy fix to a problem a lot of people are having.

**Comment by BuptStEve** [comment] 2015-10-31 02:38
@justwy It works. O(∩_∩)O thank you~

```bash
npm install jest-cli --save-dev 
npm install
```

**Comment by vmaudgalya** [comment] 2015-11-03 19:25
@justwy @trojanc @BuptStEve I am using Node v4.2.1, npm v2.14.7. Upon cloning the directory and running the following commands:
```npm install jest-cli --save-dev``` 
```npm install```

I still receive errors. Is this expected behavior?
```
npm WARN package.json react-boilerplate@0.2.0 No repository field.
npm WARN package.json react-boilerplate@0.2.0 license should be a valid SPDX license expression
npm WARN peerDependencies The peer dependency envify@~0.2.0 included from stylesheets will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency envify@~0.2.0 included from react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated react-tools@0.8.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
 
> fsevents@0.2.1 install /Users/vmaudgalya/projects/react/react-boilerplate/node_modules/jsxc/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:348:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
../node_modules/nan/nan.h:355:53: error: no member named 'New' in 'v8::String'; did you mean 'v8::TypeSwitch::New'?
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ^~~~~~~~~~~~~~~
                                                    v8::TypeSwitch::New
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/v8.h:4705:28: note: 'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:355:69: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                                    ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:357:65: error: too few arguments to function call, expected 2, have 1
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                      ~~~~~~~~~~~~~~            ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/v8.h:2499:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:357:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
../node_modules/nan/nan.h:369:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:373:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:373:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:377:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:381:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:381:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:406:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:141:71: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                      ^
../node_modules/nan/nan.h:416:12: error: no matching function for call to 'New'
    return node::Buffer::New(data, size);
           ^~~~~~~~~~~~~~~~~
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function not viable: no known conversion from 'char *' to 'v8::Isolate *' for 1st argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'char *' to 'v8::Isolate *' for 1st argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function not viable: requires 3 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:420:12: error: no matching function for call to 'New'
    return node::Buffer::New(size);
           ^~~~~~~~~~~~~~~~~
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function not viable: requires at least 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function not viable: requires 3 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:427:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(data, size);
           ~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:727:49: error: too few arguments to function call, single argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/vmaudgalya/.node-gyp/4.2.1/include/node/v8.h:2933:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/vmaudgalya/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/vmaudgalya/.nvm/versions/node/v4.2.1/bin/node" "/Users/vmaudgalya/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vmaudgalya/projects/react/react-boilerplate/node_modules/jsxc/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.2.1
```

**Comment by Troland** [comment] 2015-11-05 06:48
@justwy Thanks, it works for me.

**Comment by kyldvs** [comment] 2015-11-18 20:43
Should be resolved now, `npm install` and `npm run build` work successfully for me on:

node v4.2.1
npm 3.3.11

**Comment by maynardewm** [comment] 2015-12-08 15:34
I'm having this problem again in Node v5.1.0

    npm WARN deprecated react-tools@0.8.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
    npm WARN prefer global react-tools@0.8.0 should be installed with -g

    > fsevents@0.2.1 install /Users/erickmaynard/react-node/node_modules/fsevents
    > node-gyp rebuild

    CXX(target) Release/obj.target/fse/fsevents.o
    In file included from ../fsevents.cc:6:
    ../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
    # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
    ../../nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
    ../../nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
    # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
    ../../nan/nan.h:348:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
    ../../nan/nan.h:355:65: error: no member named 'New' in 'v8::String'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ~~~~~~~~~~~~^
    ../../nan/nan.h:357:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
    ../../nan/nan.h:357:65: error: too few arguments to function call, expected 2,
      have 1
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                      ~~~~~~~~~~~~~~            ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/v8.h:2496:3: note: 'New' declared
      here
    static Local<Integer> New(Isolate* isolate, int32_t value);
    ^
    In file included from ../fsevents.cc:6:
    ../../nan/nan.h:369:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
    # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
    ../../nan/nan.h:373:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
    ../../nan/nan.h:373:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
    # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
    ../../nan/nan.h:377:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
    # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
    ../../nan/nan.h:381:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
    ../../nan/nan.h:381:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
    # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
    ../../nan/nan.h:406:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
    ../../nan/nan.h:141:71: note: expanded from macro 'NAN_INLINE'
    # define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                      ^
    ../../nan/nan.h:416:12: error: no matching function for call to 'New'
    return node::Buffer::New(data, size);
           ^~~~~~~~~~~~~~~~~
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:28:40: note: 
      candidate function not viable: no known conversion from 'char *' to
      'v8::Isolate *' for 1st argument
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: no known conversion from 'char *' to
      'v8::Isolate *' for 1st argument
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:43:40: note: 
      candidate function not viable: requires 3 arguments, but 2 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:36:40: note: 
      candidate function not viable: requires 5 arguments, but 2 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
    In file included from ../fsevents.cc:6:
    ../../nan/nan.h:420:12: error: no matching function for call to 'New'
    return node::Buffer::New(size);
           ^~~~~~~~~~~~~~~~~
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:28:40: note: 
      candidate function not viable: requires 2 arguments, but 1 was provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: requires at least 2 arguments, but 1 was
      provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:43:40: note: 
      candidate function not viable: requires 3 arguments, but 1 was provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/node_buffer.h:36:40: note: 
      candidate function not viable: requires 5 arguments, but 1 was provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
    In file included from ../fsevents.cc:6:
    ../../nan/nan.h:427:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(data, size);
           ~~~~~~~~~~~~~~^
    ../../nan/nan.h:727:49: error: too few arguments to function call, single argument
      'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/v8.h:2930:3: note: 'New' declared
      here
    static Local<Object> New(Isolate* isolate);
    ^
    In file included from ../fsevents.cc:6:
    ../../nan/nan.h:733:49: error: too few arguments to function call, single argument
      'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
    /Users/erickmaynard/.node-gyp/5.1.0/include/node/v8.h:2930:3: note: 'New' declared
      here
    static Local<Object> New(Isolate* isolate);
    ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make: *** [Release/obj.target/fse/fsevents.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 15.0.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/erickmaynard/react-node/node_modules/fsevents
    gyp ERR! node -v v5.1.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    npm WARN install:fsevents@0.2.1 fsevents@0.2.1 install: `node-gyp rebuild`
    npm WARN install:fsevents@0.2.1 Exit status 1
    react-boilerplate@0.2.0 /Users/erickmaynard/react-node
    ├── UNMET PEER DEPENDENCY envify@~0.2.0
    ├─┬ jsxc@0.1.6 
    │ ├─┬ chokidar@0.8.4 
    │ │ └── recursive-readdir@0.0.2 
    │ ├─┬ glob@3.2.11 
    │ │ └── minimatch@0.3.0 
    │ ├── mkdirp@0.3.5 
    │ └─┬ react-tools@0.8.0 
    │   ├─┬ commoner@0.8.15 
    │   │ ├── graceful-fs@2.0.3 
    │   │ ├── install@0.4.0 
    │   │ ├── private@0.1.6 
    │   │ ├── q@1.4.1 
    │   │ ├─┬ recast@0.5.27 
    │   │ │ ├── ast-types@0.3.38 
    │   │ │ ├── cls@0.1.5 
    │   │ │ ├── esprima@1.1.0-dev-harmony  (git+https://github.com/ariya/esprima.git#a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd)
    │   │ │ └── source-map@0.1.32 
    │   │ └─┬ whiskey@0.6.13 
    │   │   ├── gex@0.0.1 
    │   │   ├── logmagic@0.1.4 
    │   │   ├── magic-templates@0.1.1 
    │   │   ├── rimraf@1.0.1 
    │   │   ├── simplesets@1.1.6 
    │   │   ├── sprintf@0.1.5 
    │   │   ├── terminal@0.1.3 
    │   │   └── underscore@1.8.3 
    │   ├── esprima-fb@2001.1001.0-dev-harmony-fb 
    │   └─┬ jstransform@2.0.3 
    │     ├── base62@0.1.1 
    │     ├── esprima-fb@2001.1001.0-dev-harmony-fb 
    │     └── source-map@0.1.31 
    ├── react@0.8.0 
    ├─┬ statics-stylesheets@0.0.1 
    │ ├─┬ fs-extra@0.8.1 
    │ │ ├── jsonfile@1.1.1 
    │ │ ├── mkdirp@0.3.5 
    │ │ ├── ncp@0.4.2 
    │ │ └── rimraf@2.2.8 
    │ ├─┬ glob@3.2.11 
    │ │ └── minimatch@0.3.0 
    │ ├── mimetype@0.0.5 
    │ └─┬ rework@0.19.0 
    │   ├── color-parser@0.1.0 
    │   ├─┬ commander@1.0.4 
    │   │ └── keypress@0.1.0 
    │   ├─┬ css@1.4.4 
    │   │ ├── css-parse@1.6.0 
    │   │ └── css-stringify@1.3.2 
    │   ├─┬ debug@2.2.0 
    │   │ └── ms@0.7.1 
    │   ├── hsb2rgb@1.0.2 
    │   ├── mime@1.2.11 
    │   ├── rework-inherit@0.2.1 
    │   └── rework-visit@1.0.0 
    └── stylesheets@0.0.5 

    npm WARN EPEERINVALID stylesheets@0.0.5 requires a peer of envify@~0.2.0 but none was installed.
    npm WARN EPEERINVALID react@0.8.0 requires a peer of envify@~0.2.0 but none was installed.
    npm WARN EPACKAGEJSON react-boilerplate@0.2.0 No repository field.
    npm WARN EPACKAGEJSON react-boilerplate@0.2.0 license should be a valid SPDX license expression

**Comment by Koshub** [comment] 2016-01-04 15:17
:+1:

**Comment by Koshub** [comment] 2016-01-04 15:22
Why it is not reopened?

**Comment by zpao** [comment] 2016-01-04 17:44
@kyldvs - this is in reference to the tutorial (https://facebook.github.io/flux/docs/todo-list.html) which mentions using react-boilerplate (https://github.com/petehunt/react-boilerplate) as a starting point. That doesn't work. /examples/flux-todomvc does work but it also doesn't use the react-boilerplate project. This should be fixed.

**Comment by C-F-K** [comment] 2016-01-20 13:02
:+1:

I don't know whether to be proud or ashamed that I absolutely exhausted my options for making the tutorial work as written before questioning why it uses a clearly deprecated boilerplate repo (it's kind of like admitting defeat, but this was not particularly efficient) but yeah, this should be fixed. 

[This tutorial](https://github.com/reactjs/react-tutorial) is really great; it doesn't seem like it'd be too hard to knock together a similar repo. (I'd do it myself, but I'm trying to learn Flux here - kind of a bootstrapping problem.)

**Comment by sylvainlap** [comment] 2016-02-04 14:59
+1

**Comment by jimmy0x52** [comment] 2016-04-18 17:26
I used `nvm` to install node `4.2.1` (as @kyldvs said it worked for him on that version). I was then able to run @justwy 's solution and `npm install` executed without error.

**Comment by kyldvs** [comment] 2016-12-16 02:05
I killed the old examples, everything under https://github.com/facebook/flux/tree/master/examples should now work and npm install fine.

**Closed by kyldvs** 2016-12-16 02:05 UTC
Labels: bug, examples
